// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {vault} from '../models';

export function AddApiKey(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AddFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddPassword(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AddProvider(arg1:main.AddProviderRequest):Promise<void>;

export function AddTotp(arg1:string,arg2:string):Promise<void>;

export function ChangePassphrase(arg1:string,arg2:string):Promise<void>;

export function CreateVault():Promise<void>;

export function CreateVaultWithPassphrase(arg1:string):Promise<void>;

export function Distribute():Promise<void>;

export function GeneratePassword():Promise<string>;

export function GetApiKey(arg1:string,arg2:string):Promise<string>;

export function GetAutoLockTimeout():Promise<number>;

export function GetDebugInfo():Promise<string>;

export function GetDistributeStatus():Promise<main.DistributeStatus>;

export function GetFile(arg1:string):Promise<string>;

export function GetPassword(arg1:string,arg2:string):Promise<string>;

export function GetProviderTypes():Promise<Array<main.ProviderTypes>>;

export function GetTotpCode(arg1:string):Promise<string>;

export function GetTotpSecondsRemaining():Promise<number>;

export function HasBiometricKey():Promise<boolean>;

export function ImportCSV(arg1:string):Promise<number>;

export function ImportTOTP(arg1:string):Promise<number>;

export function InstallCLI():Promise<void>;

export function IsCLIInstalled():Promise<boolean>;

export function IsInitialized():Promise<boolean>;

export function IsLocked():Promise<boolean>;

export function ListApiKeys():Promise<Array<vault.ApiKeyEntry>>;

export function ListFiles():Promise<Array<vault.FileEntry>>;

export function ListPasswords():Promise<Array<vault.PasswordEntry>>;

export function ListProviders():Promise<Array<main.ProviderInfo>>;

export function ListTotpServices():Promise<Array<vault.TotpService>>;

export function Lock():Promise<void>;

export function RemoveApiKey(arg1:string,arg2:string):Promise<void>;

export function RemoveFile(arg1:string):Promise<void>;

export function RemovePassword(arg1:string,arg2:string):Promise<void>;

export function RemoveProvider(arg1:string):Promise<void>;

export function RemoveTotp(arg1:string):Promise<void>;

export function Restore():Promise<void>;

export function SearchPasswords(arg1:string):Promise<Array<vault.PasswordEntry>>;

export function SetAutoLockTimeout(arg1:number):Promise<void>;

export function UnlockWithBiometric():Promise<void>;

export function UnlockWithPassphrase(arg1:string):Promise<void>;
