// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddApiKey(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddApiKey'](arg1, arg2, arg3, arg4);
}

export function AddFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddFile'](arg1, arg2, arg3);
}

export function AddPassword(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddPassword'](arg1, arg2, arg3, arg4);
}

export function AddProvider(arg1) {
  return window['go']['main']['App']['AddProvider'](arg1);
}

export function AddTotp(arg1, arg2) {
  return window['go']['main']['App']['AddTotp'](arg1, arg2);
}

export function ChangePassphrase(arg1, arg2) {
  return window['go']['main']['App']['ChangePassphrase'](arg1, arg2);
}

export function CreateVault() {
  return window['go']['main']['App']['CreateVault']();
}

export function CreateVaultWithPassphrase(arg1) {
  return window['go']['main']['App']['CreateVaultWithPassphrase'](arg1);
}

export function Distribute() {
  return window['go']['main']['App']['Distribute']();
}

export function GeneratePassword() {
  return window['go']['main']['App']['GeneratePassword']();
}

export function GetApiKey(arg1, arg2) {
  return window['go']['main']['App']['GetApiKey'](arg1, arg2);
}

export function GetAutoLockTimeout() {
  return window['go']['main']['App']['GetAutoLockTimeout']();
}

export function GetDebugInfo() {
  return window['go']['main']['App']['GetDebugInfo']();
}

export function GetDistributeStatus() {
  return window['go']['main']['App']['GetDistributeStatus']();
}

export function GetFile(arg1) {
  return window['go']['main']['App']['GetFile'](arg1);
}

export function GetPassword(arg1, arg2) {
  return window['go']['main']['App']['GetPassword'](arg1, arg2);
}

export function GetProviderTypes() {
  return window['go']['main']['App']['GetProviderTypes']();
}

export function GetTotpCode(arg1) {
  return window['go']['main']['App']['GetTotpCode'](arg1);
}

export function GetTotpSecondsRemaining() {
  return window['go']['main']['App']['GetTotpSecondsRemaining']();
}

export function HasBiometricKey() {
  return window['go']['main']['App']['HasBiometricKey']();
}

export function ImportCSV(arg1) {
  return window['go']['main']['App']['ImportCSV'](arg1);
}

export function ImportTOTP(arg1) {
  return window['go']['main']['App']['ImportTOTP'](arg1);
}

export function InstallCLI() {
  return window['go']['main']['App']['InstallCLI']();
}

export function IsCLIInstalled() {
  return window['go']['main']['App']['IsCLIInstalled']();
}

export function IsInitialized() {
  return window['go']['main']['App']['IsInitialized']();
}

export function IsLocked() {
  return window['go']['main']['App']['IsLocked']();
}

export function ListApiKeys() {
  return window['go']['main']['App']['ListApiKeys']();
}

export function ListFiles() {
  return window['go']['main']['App']['ListFiles']();
}

export function ListPasswords() {
  return window['go']['main']['App']['ListPasswords']();
}

export function ListProviders() {
  return window['go']['main']['App']['ListProviders']();
}

export function ListTotpServices() {
  return window['go']['main']['App']['ListTotpServices']();
}

export function Lock() {
  return window['go']['main']['App']['Lock']();
}

export function RemoveApiKey(arg1, arg2) {
  return window['go']['main']['App']['RemoveApiKey'](arg1, arg2);
}

export function RemoveFile(arg1) {
  return window['go']['main']['App']['RemoveFile'](arg1);
}

export function RemovePassword(arg1, arg2) {
  return window['go']['main']['App']['RemovePassword'](arg1, arg2);
}

export function RemoveProvider(arg1) {
  return window['go']['main']['App']['RemoveProvider'](arg1);
}

export function RemoveTotp(arg1) {
  return window['go']['main']['App']['RemoveTotp'](arg1);
}

export function Restore() {
  return window['go']['main']['App']['Restore']();
}

export function SearchPasswords(arg1) {
  return window['go']['main']['App']['SearchPasswords'](arg1);
}

export function SetAutoLockTimeout(arg1) {
  return window['go']['main']['App']['SetAutoLockTimeout'](arg1);
}

export function UnlockWithBiometric() {
  return window['go']['main']['App']['UnlockWithBiometric']();
}

export function UnlockWithPassphrase(arg1) {
  return window['go']['main']['App']['UnlockWithPassphrase'](arg1);
}
